Creando la base del juego
asus753/memotest pull request #1
Opened 2019-12-13 02:33 UTC by asus753

Agregando imagenes, maquetacion de la pagina y funciones mas basicas

2020-01-01 22:11 UTC, fsodano commented on index.html
> +				<img src="imagenes\Fondo.jpg" class="carta" width="165" height="165" alt="parte-trasera">
es preferible usar el formato unix y poner 'imagenes/fondo.jpg'. Además casi seguro que en el mundo real vas a usar linux para servir tu sitio web y no windows, por lo que mayúsculas y minúsculas te pueden cagar la vida. ponele `fondo.jpg` (sin mayúscula) y listo, te olvidás.

2020-01-01 22:12 UTC, fsodano commented on index.js
> +let una_ya_dada_vuelta=0
ojo que esto no es python :D . Si bien no está mal esta nomenclatura, generalmente vas a encontrar camelCase

2020-01-01 22:13 UTC, fsodano commented on index.js
> +}
Todo esto lo podés hacer en 1 sola función que sirva para cada imagen, en vez de 15 imágenes. Ponete a pensar eso :)

2020-01-01 22:13 UTC, fsodano requested changes
Muy bueno todo che! Fijate de optimizar esa función que se repite 15 veces y listo!

2020-01-11 18:14 UTC, asus753 commented on index.js
> +let una_ya_dada_vuelta=0
Te referías a las mayúsculas y minúsculas? ahí ya le puse minúscula a todo

2020-01-11 18:15 UTC, asus753 commented on index.js
> +}
Listo, resuelto :)

2020-01-11 18:19 UTC, asus753 commented
Juego memotest terminado.

2020-01-11 18:20 UTC, merged