Cypress
asus753/memotest pull request #2
Opened 2020-01-12 05:55 UTC by asus753

Testeo del juego con cypess

2020-01-13 20:33 UTC, fsodano commented on src/index.js
> +			cartas_boca_arriba.forEach(e => {
en general en JavaScript se usa la nomenclatura de camelCase, es decir `cartasBocaArriba`

2020-01-18 22:21 UTC, fsodano commented on cypress/integration/memotes2.js
> +let diccionario_cartas={
A menos que lo vayas a cambiar, esto puede ser un `const`

2020-01-18 22:24 UTC, fsodano commented on cypress/integration/memotes2.js
> +		cy.wrap(primera_vuelta).should('not.deep.equal', segunda_vuelta)
👏

2020-01-18 22:26 UTC, fsodano commented on cypress/integration/memotes2.js
> +                    cy.get(e).click().then(carta => {
por qué le hacés click?

2020-01-18 22:27 UTC, fsodano commented on cypress/integration/memotes2.js
> +        })
👍

2020-01-18 22:29 UTC, fsodano commented on cypress/integration/memotes2.js
> +}
te invito a que pienses una forma de que esto sea más mantenible, es decir, que no tengas que agregar otro `if` cada vez que agregás un tipo de carta más, o cada vez que modificás un tipo de carta.

2020-01-18 22:38 UTC, fsodano commented on cypress/integration/memotes2.js
> +let diccionario_cartas={
abajo estás repitiendo exactamente la misma estructura para vaciar el diccionario.

Una opción mejor es esta:

```javascript
function obtenerDiccionarioCartasVacio(){
  let diccionario_cartas;
  const diccionario_cartas_original = {
    banana: [],
    manzana: [],
    //etc...
  }
 
  //esto es necesario porque los objetos se pasan por referencia y no por valor... ejemplo:
  // x = y = 1; y = 2; //x sigue valiendo 1, pero y ahora vale 2.
  // x = y = {z: true}; y.z = false; //x.z es false, y.z es false. 
  return Object.assign({}, diccionario_cartas_original); //clona el objeto original.
}

let diccionario_cartas = obtenerDiccionarioCartasVacio();


function vaciarDiccionario(diccionario){
    diccionario=obtenerDiccionarioCartasVacio();
}

// cuando quieras vaciar el diccionario, lo pasás como parámetro

vaciarDiccionario(diccionario_cartas);
```

2020-01-18 22:40 UTC, fsodano commented on package.json
>      "boostrap": "^2.0.0",
ojo con esto. borralo `npm remove boostrap`

2020-01-18 22:41 UTC, fsodano requested changes
Ahí te dejé algunos comentarios!

2020-01-19 20:18 UTC, asus753 commented on cypress/integration/memotes2.js
> +                    cy.get(e).click().then(carta => {
Hice el juego de tal forma que es imposible saber que fruta se esconde en esa carta sin hacerle click antes

2020-01-19 20:18 UTC, asus753 commented on cypress/integration/memotes2.js
> +                    cy.get(e).click().then(carta => {
Hice el juego de tal forma que es imposible saber que fruta se esconde en esa carta sin hacerle click antes

2020-01-19 20:30 UTC, asus753 commented on package.json
>      "boostrap": "^2.0.0",
Estuve intentando, pero no se me borra, únicamente me lo saca de "devDependencies". Nose si borrarlo manualmente sirva

2020-01-19 20:41 UTC, asus753 commented on package.json
>      "boostrap": "^2.0.0",
Ya esta, me estaba equivocando con una letra

2020-01-20 01:58 UTC, asus753 commented on cypress/integration/memotes2.js
> +let diccionario_cartas={
```return Object.assign({}, diccionario_cartas_original)
```
Si yo en vez de poner esa linea pondría `return diccionario_cartas_original`, sucedería lo que me explicaste arriba? No lo termine de entender del todo bien, pero ya me voy a poner a leer en MDN

2020-01-20 18:00 UTC, asus753 commented on cypress/integration/memotes2.js
> +}
Ahi recien lo modifique para que, si es la primera vez que aparece esa fruta, tiene que crear en el diccionario una nueva propiedad con el nombre de la fruta y guardar el elemento HTML en ella; en cambio si es la segunda vez que aparece, solamente tiene que guardar el elemento HTML dentro de la propiedad correspondiente

```
function agrupar_cartas(e){
    
    const frutaCarta = e.src.replace("http://192.168.1.37:8080/imagenes/", "").replace(".jpg", "") //funciona

    if(diccionario_cartas[frutaCarta]){
        diccionario_cartas[frutaCarta].push(e)
    }else{
        diccionario_cartas[frutaCarta] = [e]
    }

}
```

2020-01-23 08:31 UTC, fsodano commented on cypress/integration/memotes2.js
> +let diccionario_cartas={
Tiene que ver con variables por referencia o por valor. Si vos devolvés "return diccionario_cartas_original", el problema es que en cuanto modifiques ese diccionario, perdés el original. Por eso devolvés un clon, porque los objetos se pasan por referencia.

`x = y = {z: true}; y.z = false; //x.z es false, y.z es false. `

Esto te da la pauta de que no es que x e y tienen los mismos valores si no que x e y apuntan exactamente al mismo objeto.

2020-01-25 23:03 UTC, fsodano commented on cypress/integration/memotes2.js
> +                    cy.get(e).click().then(carta => {
ok

2020-01-25 23:03 UTC, fsodano approved these changes

2020-02-11 14:35 UTC, merged